{ lib, pkgs, firefoxPwaLauncher ? null, ... }:
let
  # Encode the first 128 SHA-256 bits as Crockford Base32. Two leading zero
  # bits keep the first digit <= 7, as required by the ULID parser.
  # This is generated by AI ... I know the intention, but I don't know how it works.
  mkStableId = namespace: value:
    let
      hex = lib.stringToCharacters "0123456789abcdef";
      alphabet = lib.stringToCharacters "0123456789ABCDEFGHJKMNPQRSTVWXYZ";
      nibbleBits = [
        "0000" "0001" "0010" "0011" "0100" "0101" "0110" "0111"
        "1000" "1001" "1010" "1011" "1100" "1101" "1110" "1111"
      ];
      bitsByHex = builtins.listToAttrs (lib.imap0 (i: name: {
        inherit name;
        value = builtins.elemAt nibbleBits i;
      }) hex);
      digest = builtins.substring 0 32 (builtins.hashString "sha256"
        (builtins.toJSON [ "gnm.hm.pwaFirefox.v1" namespace value ]));
      bits = "00" + lib.concatMapStrings (c: bitsByHex.${c})
        (lib.stringToCharacters digest);
      digit = index:
        let
          chunk = lib.stringToCharacters (builtins.substring (index * 5) 5 bits);
          n = builtins.foldl' (acc: bit: acc * 2 + (if bit == "1" then 1 else 0)) 0 chunk;
        in builtins.elemAt alphabet n;
    in lib.concatStrings (builtins.genList digit 26);

  appIcon = app: with lib;
    let source = if app.iconUrl != null then app.iconUrl else app.icon;
    in if source == null then null
    else if builtins.isPath source then source
    else if hasPrefix "https://" source || hasPrefix "http://" source then
      pkgs.fetchurl {
        url = source;
        hash = if app.iconHash != null then app.iconHash
          else throw "pwaFirefox: remote icon for ${app.title} requires iconHash.";
        name = "firefoxpwa-${app.id}-icon";
      }
    else if hasPrefix "/" source || hasPrefix "./" source || hasPrefix "../" source then
      throw "pwaFirefox: use a Nix path literal for ${app.title}'s icon."
    else source;

  appModule = { config, ... }: with lib; {
    options = {
      title = mkOption {
        type = types.str;
        description = "Display name; may change without changing an explicit id.";
      };
      id = mkOption {
        type = types.strMatching "[a-z0-9][a-z0-9_-]*";
        default = toLower (replaceStrings [ " " ] [ "-" ] config.title);
        description = "Stable app key. Set explicitly before first use; keep unchanged to retain data.";
      };
      profile = mkOption {
        type = types.strMatching "[a-z0-9][a-z0-9_-]*";
        default = config.id;
        description = "Stable profile key. Apps with the same key share cookies, login and browser data.";
      };
      url = mkOption {
        type = types.strMatching "https?://[^[:space:]]+";
        description = "Start URL.";
      };
      manifestUrl = mkOption {
        type = types.nullOr types.str;
        default = null;
        description = "Optional web manifest URL. Null also supports ordinary websites.";
      };
      icon = mkOption {
        type = types.nullOr (types.either types.path types.str);
        default = null;
        description = "Local Nix path literal, icon-theme name, or pinned remote URL.";
      };
      iconUrl = mkOption {
        type = types.nullOr types.str;
        default = null;
        description = "Remote icon URL; requires iconHash. Mutually exclusive with icon.";
      };
      iconHash = mkOption {
        type = types.nullOr types.str;
        default = null;
        description = "Fixed-output hash for a remote icon.";
      };
      categories = mkOption {
        type = types.listOf types.str;
        default = [ "Network" ];
        description = "Desktop entry categories.";
      };
      singleInstance = mkOption {
        type = types.bool;
        default = true;
        description = "Whether to allow only a single instance of the app.";
      };
    };
  };
  
  pwaDesktopEntry = app:
    let
      title = app.title;
      singleInstanceString = if app.singleInstance or true then "1" else "0";
      iconPath = appIcon app;
      desktopEntry = {
        name = title;
        genericName = title;
        exec = "${firefoxPwaLauncher} ${mkStableId "site" app.id} ${singleInstanceString}";
        terminal = false;
        categories = app.categories or [];
        startupNotify = true;
        settings = {
          StartupWMClass = title;
        };
      };
    in if iconPath == null then desktopEntry else desktopEntry // { icon = toString iconPath; };

  site = app: {
      name = app.title;
      inherit (app) url manifestUrl;
    };
in {
  inherit mkStableId appIcon appModule site pwaDesktopEntry;
}
