{ lib, pkgs, ... }:
let
  # Encode the first 128 SHA-256 bits as Crockford Base32. Two leading zero
  # bits keep the first digit <= 7, as required by the ULID parser.
  # This is generated by AI ... I know the intention, but I don't know how it works.
  mkStableId = namespace: value:
    let
      hex = lib.stringToCharacters "0123456789abcdef";
      alphabet = lib.stringToCharacters "0123456789ABCDEFGHJKMNPQRSTVWXYZ";
      nibbleBits = [
        "0000" "0001" "0010" "0011" "0100" "0101" "0110" "0111"
        "1000" "1001" "1010" "1011" "1100" "1101" "1110" "1111"
      ];
      bitsByHex = builtins.listToAttrs (lib.imap0 (i: name: {
        inherit name;
        value = builtins.elemAt nibbleBits i;
      }) hex);
      digest = builtins.substring 0 32 (builtins.hashString "sha256"
        (builtins.toJSON [ "gnm.hm.pwaFirefox.v1" namespace value ]));
      bits = "00" + lib.concatMapStrings (c: bitsByHex.${c})
        (lib.stringToCharacters digest);
      digit = index:
        let
          chunk = lib.stringToCharacters (builtins.substring (index * 5) 5 bits);
          n = builtins.foldl' (acc: bit: acc * 2 + (if bit == "1" then 1 else 0)) 0 chunk;
        in builtins.elemAt alphabet n;
    in lib.concatStrings (builtins.genList digit 26);

  appIcon = app:
    let source = if app.iconUrl != null then app.iconUrl else app.icon;
    in if source == null then null
    else if builtins.isPath source then source
    else if lib.hasPrefix "https://" source || lib.hasPrefix "http://" source then
      pkgs.fetchurl {
        url = source;
        hash = if app.iconHash != null then app.iconHash
          else throw "pwaFirefox: remote icon for ${app.title} requires iconHash.";
        name = "firefoxpwa-${app.id}-icon";
      }
    else if lib.hasPrefix "/" source || lib.hasPrefix "./" source || lib.hasPrefix "../" source then
      throw "pwaFirefox: use a Nix path literal for ${app.title}'s icon."
    else source;

  appModule = { config, ... }: {
    options = {
      title = lib.mkOption {
        type = lib.types.str;
        description = "Display name; may change without changing an explicit id.";
      };
      id = lib.mkOption {
        type = lib.types.strMatching "[a-z0-9][a-z0-9_-]*";
        default = lib.toLower (lib.replaceStrings [ " " ] [ "-" ] config.title);
        description = "Stable app key. Set explicitly before first use; keep unchanged to retain data.";
      };
      profile = lib.mkOption {
        type = lib.types.strMatching "[a-z0-9][a-z0-9_-]*";
        default = config.id;
        description = "Stable profile key. Apps with the same key share cookies, login and browser data.";
      };
      url = lib.mkOption {
        type = lib.types.strMatching "https?://[^[:space:]]+";
        description = "Start URL.";
      };
      manifestUrl = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        description = "Optional web manifest URL. Null also supports ordinary websites.";
      };
      icon = lib.mkOption {
        type = lib.types.nullOr (lib.types.either lib.types.path lib.types.str);
        default = null;
        description = "Local Nix path literal, icon-theme name, or pinned remote URL.";
      };
      iconUrl = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        description = "Remote icon URL; requires iconHash. Mutually exclusive with icon.";
      };
      iconHash = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        description = "Fixed-output hash for a remote icon.";
      };
      categories = lib.mkOption {
        type = lib.types.listOf lib.types.str;
        default = [ "Network" ];
        description = "Desktop entry categories.";
      };
    };
  };

  site = app: {
    name = app.title;
    inherit (app) url manifestUrl;
    desktopEntry = {
      icon = appIcon app;
      inherit (app) categories;
    };
  };
in {
  inherit mkStableId appIcon appModule site;
}
