{pkgs, ...}: {
  programs.fzf = {
    enable = true;

    enableBashIntegration = true;
    enableFishIntegration = true;
    enableZshIntegration = true;
    # the theme is generated by stylix, but still - theme generator: 
    #    https://vitormv.github.io/fzf-themes/
    defaultOptions = [
      "--info=inline-right"
      "--preview-window='border-rounded'"
      "--padding='1'"
      "--margin='1'"
      "--layout='reverse'"
    ];
    # regarding options: https://github.com/junegunn/fzf?tab=readme-ov-file#key-bindings-for-command-line
    # alt-c options
    changeDirWidgetOptions = [
      "--preview 'eza --group-directories-first --no-quotes --no-permissions --no-user --no-git --icons --color=always {}'"
    ];
    # ctrl-t options
    fileWidgetOptions = [
      "--preview='bat -n --color=always {}'"
      "--bind 'ctrl-/:change-preview-window(down|hidden|)'"
    ];
    # ctrl-r options
    historyWidgetOptions = [ 
      "--no-multi"
    ];
  };

  programs.fish = {
    # is this even still needed?
    plugins = with pkgs.fishPlugins; [
      {
        name = "fzf";
        inherit (fzf) src;
      }
      {
        name = "fzf-fish";
        inherit (fzf-fish) src;
      } # requires fd and bat
    ];
    shellAbbrs.fzf-help = "fzf_configure_bindings --help";
    # ctrl-o = edit file, ctrl-g = xdg-open
    interactiveShellInit = ''
      set fzf_directory_opts --bind "ctrl-o:execute($EDITOR {} &> /dev/tty)"
    '';
  };

  home.packages = [pkgs.fd pkgs.bat];
}